language: node_js
node_js:
  - "node"
  - "7"

cache:
  directories:
    - "node_modules"

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always/hideURL=true
